name: XIAMS_PIV

on:
  push:
    branches: [agg-report]

  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: agg-report
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test
        continue-on-error: true
         
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: build/reports/cucumber_reports