name: XIAMS_PIV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test
        continue-on-error: true

      - name: Set environment variables
        run: |
          echo "REGION=ap-southeast-2" >> $GITHUB_ENV
          echo "S3_BUCKET=ctaas-enterprise-poc/${{github.repository}}/${GITHUB_REF#refs/heads/}/${{github.workflow}}/${{github.run_number}}" >> $GITHUB_ENV

      - name: Read file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./build/cucumber-reports/cucumber-html-reports/overview-features.html

      - name: Echo file
        run: echo "${{ steps.package.outputs.content }}"

