name: XIAMS_PIV

on:
  push:
    branches: [agg-report]

  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test
        continue-on-error: true
      
      - name: Get report directory
        run: |
          cd build/reports/cucumber_reports
         
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: cucumber_reports